stages:
  - build

build-iso:
  stage: build
  tags:
    - natalieos-shell
  before_script:
    - pacman -Syu --noconfirm archiso
  script:
    - mkdir -p out work
    - mkarchiso -v -w work -o out .
  after_script:
    - rm -rf work
  artifacts:
    name: "natalieos-${CI_COMMIT_SHORT_SHA}"
    paths:
      - out/*.iso
    expire_in: 30 days
  only:
    - main
